/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_TOOL_H
#define _MOCK_TOOL_H

#include "unity.h"
#include "Tool.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_Tool_Init(void);
void mock_Tool_Destroy(void);
void mock_Tool_Verify(void);




#define Tool_Init_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Tool_Init requires _Ignore (not AndReturn)");
#define Tool_Init_Ignore() Tool_Init_CMockIgnore()
void Tool_Init_CMockIgnore(void);
#define Tool_Init_StopIgnore() Tool_Init_CMockStopIgnore()
void Tool_Init_CMockStopIgnore(void);
#define Tool_Init_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Tool_Init requires _Expect (not AndReturn)");
#define Tool_Init_Expect() Tool_Init_CMockExpect(__LINE__)
void Tool_Init_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_Tool_Init_CALLBACK)(int cmock_num_calls);
void Tool_Init_AddCallback(CMOCK_Tool_Init_CALLBACK Callback);
void Tool_Init_Stub(CMOCK_Tool_Init_CALLBACK Callback);
#define Tool_Init_StubWithCallback Tool_Init_Stub
#define Tool_DeInit_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Tool_DeInit requires _Ignore (not AndReturn)");
#define Tool_DeInit_Ignore() Tool_DeInit_CMockIgnore()
void Tool_DeInit_CMockIgnore(void);
#define Tool_DeInit_StopIgnore() Tool_DeInit_CMockStopIgnore()
void Tool_DeInit_CMockStopIgnore(void);
#define Tool_DeInit_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Tool_DeInit requires _Expect (not AndReturn)");
#define Tool_DeInit_Expect() Tool_DeInit_CMockExpect(__LINE__)
void Tool_DeInit_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_Tool_DeInit_CALLBACK)(int cmock_num_calls);
void Tool_DeInit_AddCallback(CMOCK_Tool_DeInit_CALLBACK Callback);
void Tool_DeInit_Stub(CMOCK_Tool_DeInit_CALLBACK Callback);
#define Tool_DeInit_StubWithCallback Tool_DeInit_Stub
#define Tool_SetMode_u8_Ignore() TEST_FAIL_MESSAGE("Tool_SetMode_u8 requires _IgnoreAndReturn");
#define Tool_SetMode_u8_IgnoreAndReturn(cmock_retval) Tool_SetMode_u8_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void Tool_SetMode_u8_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define Tool_SetMode_u8_StopIgnore() Tool_SetMode_u8_CMockStopIgnore()
void Tool_SetMode_u8_CMockStopIgnore(void);
#define Tool_SetMode_u8_ExpectAnyArgs() TEST_FAIL_MESSAGE("Tool_SetMode_u8 requires _ExpectAnyArgsAndReturn");
#define Tool_SetMode_u8_ExpectAnyArgsAndReturn(cmock_retval) Tool_SetMode_u8_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void Tool_SetMode_u8_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define Tool_SetMode_u8_Expect(mode) TEST_FAIL_MESSAGE("Tool_SetMode_u8 requires _ExpectAndReturn");
#define Tool_SetMode_u8_ExpectAndReturn(mode, cmock_retval) Tool_SetMode_u8_CMockExpectAndReturn(__LINE__, mode, cmock_retval)
void Tool_SetMode_u8_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, Tool_mode_e mode, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_Tool_SetMode_u8_CALLBACK)(Tool_mode_e mode, int cmock_num_calls);
void Tool_SetMode_u8_AddCallback(CMOCK_Tool_SetMode_u8_CALLBACK Callback);
void Tool_SetMode_u8_Stub(CMOCK_Tool_SetMode_u8_CALLBACK Callback);
#define Tool_SetMode_u8_StubWithCallback Tool_SetMode_u8_Stub
#define Tool_SetMode_u8_IgnoreArg_mode() Tool_SetMode_u8_CMockIgnoreArg_mode(__LINE__)
void Tool_SetMode_u8_CMockIgnoreArg_mode(UNITY_LINE_TYPE cmock_line);
#define Tool_GetStatus_u32_Ignore() TEST_FAIL_MESSAGE("Tool_GetStatus_u32 requires _IgnoreAndReturn");
#define Tool_GetStatus_u32_IgnoreAndReturn(cmock_retval) Tool_GetStatus_u32_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void Tool_GetStatus_u32_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define Tool_GetStatus_u32_StopIgnore() Tool_GetStatus_u32_CMockStopIgnore()
void Tool_GetStatus_u32_CMockStopIgnore(void);
#define Tool_GetStatus_u32_Expect() TEST_FAIL_MESSAGE("Tool_GetStatus_u32 requires _ExpectAndReturn");
#define Tool_GetStatus_u32_ExpectAndReturn(cmock_retval) Tool_GetStatus_u32_CMockExpectAndReturn(__LINE__, cmock_retval)
void Tool_GetStatus_u32_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_Tool_GetStatus_u32_CALLBACK)(int cmock_num_calls);
void Tool_GetStatus_u32_AddCallback(CMOCK_Tool_GetStatus_u32_CALLBACK Callback);
void Tool_GetStatus_u32_Stub(CMOCK_Tool_GetStatus_u32_CALLBACK Callback);
#define Tool_GetStatus_u32_StubWithCallback Tool_GetStatus_u32_Stub
#define Tool_ComputeCrc_u32_Ignore() TEST_FAIL_MESSAGE("Tool_ComputeCrc_u32 requires _IgnoreAndReturn");
#define Tool_ComputeCrc_u32_IgnoreAndReturn(cmock_retval) Tool_ComputeCrc_u32_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void Tool_ComputeCrc_u32_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define Tool_ComputeCrc_u32_StopIgnore() Tool_ComputeCrc_u32_CMockStopIgnore()
void Tool_ComputeCrc_u32_CMockStopIgnore(void);
#define Tool_ComputeCrc_u32_ExpectAnyArgs() TEST_FAIL_MESSAGE("Tool_ComputeCrc_u32 requires _ExpectAnyArgsAndReturn");
#define Tool_ComputeCrc_u32_ExpectAnyArgsAndReturn(cmock_retval) Tool_ComputeCrc_u32_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void Tool_ComputeCrc_u32_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define Tool_ComputeCrc_u32_Expect(data_pcu8, length_u32) TEST_FAIL_MESSAGE("Tool_ComputeCrc_u32 requires _ExpectAndReturn");
#define Tool_ComputeCrc_u32_ExpectAndReturn(data_pcu8, length_u32, cmock_retval) Tool_ComputeCrc_u32_CMockExpectAndReturn(__LINE__, data_pcu8, length_u32, cmock_retval)
void Tool_ComputeCrc_u32_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t* data_pcu8, uint32_t length_u32, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_Tool_ComputeCrc_u32_CALLBACK)(const uint8_t* data_pcu8, uint32_t length_u32, int cmock_num_calls);
void Tool_ComputeCrc_u32_AddCallback(CMOCK_Tool_ComputeCrc_u32_CALLBACK Callback);
void Tool_ComputeCrc_u32_Stub(CMOCK_Tool_ComputeCrc_u32_CALLBACK Callback);
#define Tool_ComputeCrc_u32_StubWithCallback Tool_ComputeCrc_u32_Stub
#define Tool_ComputeCrc_u32_ExpectWithArray(data_pcu8, data_pcu8_Depth, length_u32) TEST_FAIL_MESSAGE("Tool_ComputeCrc_u32 requires _ExpectWithArrayAndReturn");
#define Tool_ComputeCrc_u32_ExpectWithArrayAndReturn(data_pcu8, data_pcu8_Depth, length_u32, cmock_retval) Tool_ComputeCrc_u32_CMockExpectWithArrayAndReturn(__LINE__, data_pcu8, (data_pcu8_Depth), length_u32, cmock_retval)
void Tool_ComputeCrc_u32_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t* data_pcu8, int data_pcu8_Depth, uint32_t length_u32, uint32_t cmock_to_return);
#define Tool_ComputeCrc_u32_IgnoreArg_data_pcu8() Tool_ComputeCrc_u32_CMockIgnoreArg_data_pcu8(__LINE__)
void Tool_ComputeCrc_u32_CMockIgnoreArg_data_pcu8(UNITY_LINE_TYPE cmock_line);
#define Tool_ComputeCrc_u32_IgnoreArg_length_u32() Tool_ComputeCrc_u32_CMockIgnoreArg_length_u32(__LINE__)
void Tool_ComputeCrc_u32_CMockIgnoreArg_length_u32(UNITY_LINE_TYPE cmock_line);
#define Tool_Push_u8_Ignore() TEST_FAIL_MESSAGE("Tool_Push_u8 requires _IgnoreAndReturn");
#define Tool_Push_u8_IgnoreAndReturn(cmock_retval) Tool_Push_u8_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void Tool_Push_u8_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define Tool_Push_u8_StopIgnore() Tool_Push_u8_CMockStopIgnore()
void Tool_Push_u8_CMockStopIgnore(void);
#define Tool_Push_u8_ExpectAnyArgs() TEST_FAIL_MESSAGE("Tool_Push_u8 requires _ExpectAnyArgsAndReturn");
#define Tool_Push_u8_ExpectAnyArgsAndReturn(cmock_retval) Tool_Push_u8_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void Tool_Push_u8_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define Tool_Push_u8_Expect(value_u8) TEST_FAIL_MESSAGE("Tool_Push_u8 requires _ExpectAndReturn");
#define Tool_Push_u8_ExpectAndReturn(value_u8, cmock_retval) Tool_Push_u8_CMockExpectAndReturn(__LINE__, value_u8, cmock_retval)
void Tool_Push_u8_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t value_u8, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_Tool_Push_u8_CALLBACK)(uint8_t value_u8, int cmock_num_calls);
void Tool_Push_u8_AddCallback(CMOCK_Tool_Push_u8_CALLBACK Callback);
void Tool_Push_u8_Stub(CMOCK_Tool_Push_u8_CALLBACK Callback);
#define Tool_Push_u8_StubWithCallback Tool_Push_u8_Stub
#define Tool_Push_u8_IgnoreArg_value_u8() Tool_Push_u8_CMockIgnoreArg_value_u8(__LINE__)
void Tool_Push_u8_CMockIgnoreArg_value_u8(UNITY_LINE_TYPE cmock_line);
#define Tool_Pop_u8_Ignore() TEST_FAIL_MESSAGE("Tool_Pop_u8 requires _IgnoreAndReturn");
#define Tool_Pop_u8_IgnoreAndReturn(cmock_retval) Tool_Pop_u8_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void Tool_Pop_u8_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define Tool_Pop_u8_StopIgnore() Tool_Pop_u8_CMockStopIgnore()
void Tool_Pop_u8_CMockStopIgnore(void);
#define Tool_Pop_u8_ExpectAnyArgs() TEST_FAIL_MESSAGE("Tool_Pop_u8 requires _ExpectAnyArgsAndReturn");
#define Tool_Pop_u8_ExpectAnyArgsAndReturn(cmock_retval) Tool_Pop_u8_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void Tool_Pop_u8_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define Tool_Pop_u8_Expect(value_pu8) TEST_FAIL_MESSAGE("Tool_Pop_u8 requires _ExpectAndReturn");
#define Tool_Pop_u8_ExpectAndReturn(value_pu8, cmock_retval) Tool_Pop_u8_CMockExpectAndReturn(__LINE__, value_pu8, cmock_retval)
void Tool_Pop_u8_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* value_pu8, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_Tool_Pop_u8_CALLBACK)(uint8_t* value_pu8, int cmock_num_calls);
void Tool_Pop_u8_AddCallback(CMOCK_Tool_Pop_u8_CALLBACK Callback);
void Tool_Pop_u8_Stub(CMOCK_Tool_Pop_u8_CALLBACK Callback);
#define Tool_Pop_u8_StubWithCallback Tool_Pop_u8_Stub
#define Tool_Pop_u8_ExpectWithArray(value_pu8, value_pu8_Depth) TEST_FAIL_MESSAGE("Tool_Pop_u8 requires _ExpectWithArrayAndReturn");
#define Tool_Pop_u8_ExpectWithArrayAndReturn(value_pu8, value_pu8_Depth, cmock_retval) Tool_Pop_u8_CMockExpectWithArrayAndReturn(__LINE__, value_pu8, (value_pu8_Depth), cmock_retval)
void Tool_Pop_u8_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* value_pu8, int value_pu8_Depth, uint8_t cmock_to_return);
#define Tool_Pop_u8_ReturnThruPtr_value_pu8(value_pu8) Tool_Pop_u8_CMockReturnMemThruPtr_value_pu8(__LINE__, value_pu8, sizeof(uint8_t))
#define Tool_Pop_u8_ReturnArrayThruPtr_value_pu8(value_pu8, cmock_len) Tool_Pop_u8_CMockReturnMemThruPtr_value_pu8(__LINE__, value_pu8, (cmock_len * sizeof(*value_pu8)))
#define Tool_Pop_u8_ReturnMemThruPtr_value_pu8(value_pu8, cmock_size) Tool_Pop_u8_CMockReturnMemThruPtr_value_pu8(__LINE__, value_pu8, (cmock_size))
void Tool_Pop_u8_CMockReturnMemThruPtr_value_pu8(UNITY_LINE_TYPE cmock_line, uint8_t const* value_pu8, size_t cmock_size);
#define Tool_Pop_u8_IgnoreArg_value_pu8() Tool_Pop_u8_CMockIgnoreArg_value_pu8(__LINE__)
void Tool_Pop_u8_CMockIgnoreArg_value_pu8(UNITY_LINE_TYPE cmock_line);
#define Tool_RunTst_u8_Ignore() TEST_FAIL_MESSAGE("Tool_RunTst_u8 requires _IgnoreAndReturn");
#define Tool_RunTst_u8_IgnoreAndReturn(cmock_retval) Tool_RunTst_u8_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void Tool_RunTst_u8_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define Tool_RunTst_u8_StopIgnore() Tool_RunTst_u8_CMockStopIgnore()
void Tool_RunTst_u8_CMockStopIgnore(void);
#define Tool_RunTst_u8_Expect() TEST_FAIL_MESSAGE("Tool_RunTst_u8 requires _ExpectAndReturn");
#define Tool_RunTst_u8_ExpectAndReturn(cmock_retval) Tool_RunTst_u8_CMockExpectAndReturn(__LINE__, cmock_retval)
void Tool_RunTst_u8_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_Tool_RunTst_u8_CALLBACK)(int cmock_num_calls);
void Tool_RunTst_u8_AddCallback(CMOCK_Tool_RunTst_u8_CALLBACK Callback);
void Tool_RunTst_u8_Stub(CMOCK_Tool_RunTst_u8_CALLBACK Callback);
#define Tool_RunTst_u8_StubWithCallback Tool_RunTst_u8_Stub
#define ModuleName_FunctionEx__Ignore() TEST_FAIL_MESSAGE("ModuleName_FunctionEx_ requires _IgnoreAndReturn");
#define ModuleName_FunctionEx__IgnoreAndReturn(cmock_retval) ModuleName_FunctionEx__CMockIgnoreAndReturn(__LINE__, cmock_retval)
void ModuleName_FunctionEx__CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define ModuleName_FunctionEx__StopIgnore() ModuleName_FunctionEx__CMockStopIgnore()
void ModuleName_FunctionEx__CMockStopIgnore(void);
#define ModuleName_FunctionEx__ExpectAnyArgs() TEST_FAIL_MESSAGE("ModuleName_FunctionEx_ requires _ExpectAnyArgsAndReturn");
#define ModuleName_FunctionEx__ExpectAnyArgsAndReturn(cmock_retval) ModuleName_FunctionEx__CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void ModuleName_FunctionEx__CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define ModuleName_FunctionEx__Expect(in_id_u32, in_mode_e, in_cfg_pcu8, in_buf_pu8, in_bufLen_u16, out_status_pu8) TEST_FAIL_MESSAGE("ModuleName_FunctionEx_ requires _ExpectAndReturn");
#define ModuleName_FunctionEx__ExpectAndReturn(in_id_u32, in_mode_e, in_cfg_pcu8, in_buf_pu8, in_bufLen_u16, out_status_pu8, cmock_retval) ModuleName_FunctionEx__CMockExpectAndReturn(__LINE__, in_id_u32, in_mode_e, in_cfg_pcu8, in_buf_pu8, in_bufLen_u16, out_status_pu8, cmock_retval)
void ModuleName_FunctionEx__CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t in_id_u32, int32_t in_mode_e, const uint8_t* in_cfg_pcu8, uint8_t* in_buf_pu8, uint16_t in_bufLen_u16, uint8_t* out_status_pu8, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_ModuleName_FunctionEx__CALLBACK)(uint32_t in_id_u32, int32_t in_mode_e, const uint8_t* in_cfg_pcu8, uint8_t* in_buf_pu8, uint16_t in_bufLen_u16, uint8_t* out_status_pu8, int cmock_num_calls);
void ModuleName_FunctionEx__AddCallback(CMOCK_ModuleName_FunctionEx__CALLBACK Callback);
void ModuleName_FunctionEx__Stub(CMOCK_ModuleName_FunctionEx__CALLBACK Callback);
#define ModuleName_FunctionEx__StubWithCallback ModuleName_FunctionEx__Stub
#define ModuleName_FunctionEx__ExpectWithArray(in_id_u32, in_mode_e, in_cfg_pcu8, in_cfg_pcu8_Depth, in_buf_pu8, in_buf_pu8_Depth, in_bufLen_u16, out_status_pu8, out_status_pu8_Depth) TEST_FAIL_MESSAGE("ModuleName_FunctionEx_ requires _ExpectWithArrayAndReturn");
#define ModuleName_FunctionEx__ExpectWithArrayAndReturn(in_id_u32, in_mode_e, in_cfg_pcu8, in_cfg_pcu8_Depth, in_buf_pu8, in_buf_pu8_Depth, in_bufLen_u16, out_status_pu8, out_status_pu8_Depth, cmock_retval) ModuleName_FunctionEx__CMockExpectWithArrayAndReturn(__LINE__, in_id_u32, in_mode_e, in_cfg_pcu8, (in_cfg_pcu8_Depth), in_buf_pu8, (in_buf_pu8_Depth), in_bufLen_u16, out_status_pu8, (out_status_pu8_Depth), cmock_retval)
void ModuleName_FunctionEx__CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t in_id_u32, int32_t in_mode_e, const uint8_t* in_cfg_pcu8, int in_cfg_pcu8_Depth, uint8_t* in_buf_pu8, int in_buf_pu8_Depth, uint16_t in_bufLen_u16, uint8_t* out_status_pu8, int out_status_pu8_Depth, uint8_t cmock_to_return);
#define ModuleName_FunctionEx__ReturnThruPtr_in_buf_pu8(in_buf_pu8) ModuleName_FunctionEx__CMockReturnMemThruPtr_in_buf_pu8(__LINE__, in_buf_pu8, sizeof(uint8_t))
#define ModuleName_FunctionEx__ReturnArrayThruPtr_in_buf_pu8(in_buf_pu8, cmock_len) ModuleName_FunctionEx__CMockReturnMemThruPtr_in_buf_pu8(__LINE__, in_buf_pu8, (cmock_len * sizeof(*in_buf_pu8)))
#define ModuleName_FunctionEx__ReturnMemThruPtr_in_buf_pu8(in_buf_pu8, cmock_size) ModuleName_FunctionEx__CMockReturnMemThruPtr_in_buf_pu8(__LINE__, in_buf_pu8, (cmock_size))
void ModuleName_FunctionEx__CMockReturnMemThruPtr_in_buf_pu8(UNITY_LINE_TYPE cmock_line, uint8_t const* in_buf_pu8, size_t cmock_size);
#define ModuleName_FunctionEx__ReturnThruPtr_out_status_pu8(out_status_pu8) ModuleName_FunctionEx__CMockReturnMemThruPtr_out_status_pu8(__LINE__, out_status_pu8, sizeof(uint8_t))
#define ModuleName_FunctionEx__ReturnArrayThruPtr_out_status_pu8(out_status_pu8, cmock_len) ModuleName_FunctionEx__CMockReturnMemThruPtr_out_status_pu8(__LINE__, out_status_pu8, (cmock_len * sizeof(*out_status_pu8)))
#define ModuleName_FunctionEx__ReturnMemThruPtr_out_status_pu8(out_status_pu8, cmock_size) ModuleName_FunctionEx__CMockReturnMemThruPtr_out_status_pu8(__LINE__, out_status_pu8, (cmock_size))
void ModuleName_FunctionEx__CMockReturnMemThruPtr_out_status_pu8(UNITY_LINE_TYPE cmock_line, uint8_t const* out_status_pu8, size_t cmock_size);
#define ModuleName_FunctionEx__IgnoreArg_in_id_u32() ModuleName_FunctionEx__CMockIgnoreArg_in_id_u32(__LINE__)
void ModuleName_FunctionEx__CMockIgnoreArg_in_id_u32(UNITY_LINE_TYPE cmock_line);
#define ModuleName_FunctionEx__IgnoreArg_in_mode_e() ModuleName_FunctionEx__CMockIgnoreArg_in_mode_e(__LINE__)
void ModuleName_FunctionEx__CMockIgnoreArg_in_mode_e(UNITY_LINE_TYPE cmock_line);
#define ModuleName_FunctionEx__IgnoreArg_in_cfg_pcu8() ModuleName_FunctionEx__CMockIgnoreArg_in_cfg_pcu8(__LINE__)
void ModuleName_FunctionEx__CMockIgnoreArg_in_cfg_pcu8(UNITY_LINE_TYPE cmock_line);
#define ModuleName_FunctionEx__IgnoreArg_in_buf_pu8() ModuleName_FunctionEx__CMockIgnoreArg_in_buf_pu8(__LINE__)
void ModuleName_FunctionEx__CMockIgnoreArg_in_buf_pu8(UNITY_LINE_TYPE cmock_line);
#define ModuleName_FunctionEx__IgnoreArg_in_bufLen_u16() ModuleName_FunctionEx__CMockIgnoreArg_in_bufLen_u16(__LINE__)
void ModuleName_FunctionEx__CMockIgnoreArg_in_bufLen_u16(UNITY_LINE_TYPE cmock_line);
#define ModuleName_FunctionEx__IgnoreArg_out_status_pu8() ModuleName_FunctionEx__CMockIgnoreArg_out_status_pu8(__LINE__)
void ModuleName_FunctionEx__CMockIgnoreArg_out_status_pu8(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
