/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "Tool.h"
#include "Tool_Clear.h"
#include "unity.h"
#include "mock_Tool.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_Tool_Clear_ResetsRingBufferIndices(void);
extern void test_Tool_Clear_ClearsBufferContent(void);
extern void test_Tool_Clear_ClearsErrorFlag(void);
extern void test_Tool_Clear_ClearsOverflowFlag(void);
extern void test_Tool_Clear_PreservesInitFlag(void);
extern void test_Tool_Clear_ClearsOnlyErrorAndOverflowFlags(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  mock_Tool_Init();
}
static void CMock_Verify(void)
{
  mock_Tool_Verify();
}
static void CMock_Destroy(void)
{
  mock_Tool_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_Tool_Clear.c");
  run_test(test_Tool_Clear_ResetsRingBufferIndices, "test_Tool_Clear_ResetsRingBufferIndices", 26);
  run_test(test_Tool_Clear_ClearsBufferContent, "test_Tool_Clear_ClearsBufferContent", 41);
  run_test(test_Tool_Clear_ClearsErrorFlag, "test_Tool_Clear_ClearsErrorFlag", 56);
  run_test(test_Tool_Clear_ClearsOverflowFlag, "test_Tool_Clear_ClearsOverflowFlag", 68);
  run_test(test_Tool_Clear_PreservesInitFlag, "test_Tool_Clear_PreservesInitFlag", 80);
  run_test(test_Tool_Clear_ClearsOnlyErrorAndOverflowFlags, "test_Tool_Clear_ClearsOnlyErrorAndOverflowFlags", 92);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
