/* AUTOGENERATED FILE. DO NOT EDIT. */
#include "mock_Tool.h"
#include "cmock.h"
#include <setjmp.h>
#include <stdlib.h>
#include <string.h>

static const char *CMockString_ModuleName_FunctionEx_ = "ModuleName_FunctionEx_";
static const char *CMockString_Tool_ComputeCrc_u32 = "Tool_ComputeCrc_u32";
static const char *CMockString_Tool_DeInit = "Tool_DeInit";
static const char *CMockString_Tool_GetStatus_u32 = "Tool_GetStatus_u32";
static const char *CMockString_Tool_Init = "Tool_Init";
static const char *CMockString_Tool_Pop_u8 = "Tool_Pop_u8";
static const char *CMockString_Tool_Push_u8 = "Tool_Push_u8";
static const char *CMockString_Tool_RunTst_u8 = "Tool_RunTst_u8";
static const char *CMockString_Tool_SetMode_u8 = "Tool_SetMode_u8";
static const char *CMockString_data_pcu8 = "data_pcu8";
static const char *CMockString_in_bufLen_u16 = "in_bufLen_u16";
static const char *CMockString_in_buf_pu8 = "in_buf_pu8";
static const char *CMockString_in_cfg_pcu8 = "in_cfg_pcu8";
static const char *CMockString_in_id_u32 = "in_id_u32";
static const char *CMockString_in_mode_e = "in_mode_e";
static const char *CMockString_length_u32 = "length_u32";
static const char *CMockString_mode = "mode";
static const char *CMockString_out_status_pu8 = "out_status_pu8";
static const char *CMockString_value_pu8 = "value_pu8";
static const char *CMockString_value_u8 = "value_u8";

typedef struct _CMOCK_Tool_Init_CALL_INSTANCE {
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;

} CMOCK_Tool_Init_CALL_INSTANCE;

typedef struct _CMOCK_Tool_DeInit_CALL_INSTANCE {
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;

} CMOCK_Tool_DeInit_CALL_INSTANCE;

typedef struct _CMOCK_Tool_SetMode_u8_CALL_INSTANCE {
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint8_t ReturnVal;
  int CallOrder;
  Tool_mode_e Expected_mode;
  char IgnoreArg_mode;

} CMOCK_Tool_SetMode_u8_CALL_INSTANCE;

typedef struct _CMOCK_Tool_GetStatus_u32_CALL_INSTANCE {
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t ReturnVal;
  int CallOrder;

} CMOCK_Tool_GetStatus_u32_CALL_INSTANCE;

typedef struct _CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE {
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t ReturnVal;
  int CallOrder;
  const uint8_t *Expected_data_pcu8;
  uint32_t Expected_length_u32;
  int Expected_data_pcu8_Depth;
  char IgnoreArg_data_pcu8;
  char IgnoreArg_length_u32;

} CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE;

typedef struct _CMOCK_Tool_Push_u8_CALL_INSTANCE {
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint8_t ReturnVal;
  int CallOrder;
  uint8_t Expected_value_u8;
  char IgnoreArg_value_u8;

} CMOCK_Tool_Push_u8_CALL_INSTANCE;

typedef struct _CMOCK_Tool_Pop_u8_CALL_INSTANCE {
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint8_t ReturnVal;
  int CallOrder;
  uint8_t *Expected_value_pu8;
  int Expected_value_pu8_Depth;
  char ReturnThruPtr_value_pu8_Used;
  uint8_t const *ReturnThruPtr_value_pu8_Val;
  size_t ReturnThruPtr_value_pu8_Size;
  char IgnoreArg_value_pu8;

} CMOCK_Tool_Pop_u8_CALL_INSTANCE;

typedef struct _CMOCK_Tool_RunTst_u8_CALL_INSTANCE {
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint8_t ReturnVal;
  int CallOrder;

} CMOCK_Tool_RunTst_u8_CALL_INSTANCE;

typedef struct _CMOCK_ModuleName_FunctionEx__CALL_INSTANCE {
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint8_t ReturnVal;
  int CallOrder;
  uint32_t Expected_in_id_u32;
  int32_t Expected_in_mode_e;
  const uint8_t *Expected_in_cfg_pcu8;
  uint8_t *Expected_in_buf_pu8;
  uint16_t Expected_in_bufLen_u16;
  uint8_t *Expected_out_status_pu8;
  int Expected_in_cfg_pcu8_Depth;
  int Expected_in_buf_pu8_Depth;
  int Expected_out_status_pu8_Depth;
  char ReturnThruPtr_in_buf_pu8_Used;
  uint8_t const *ReturnThruPtr_in_buf_pu8_Val;
  size_t ReturnThruPtr_in_buf_pu8_Size;
  char ReturnThruPtr_out_status_pu8_Used;
  uint8_t const *ReturnThruPtr_out_status_pu8_Val;
  size_t ReturnThruPtr_out_status_pu8_Size;
  char IgnoreArg_in_id_u32;
  char IgnoreArg_in_mode_e;
  char IgnoreArg_in_cfg_pcu8;
  char IgnoreArg_in_buf_pu8;
  char IgnoreArg_in_bufLen_u16;
  char IgnoreArg_out_status_pu8;

} CMOCK_ModuleName_FunctionEx__CALL_INSTANCE;

static struct mock_ToolInstance {
  char Tool_Init_IgnoreBool;
  char Tool_Init_CallbackBool;
  CMOCK_Tool_Init_CALLBACK Tool_Init_CallbackFunctionPointer;
  int Tool_Init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Tool_Init_CallInstance;
  char Tool_DeInit_IgnoreBool;
  char Tool_DeInit_CallbackBool;
  CMOCK_Tool_DeInit_CALLBACK Tool_DeInit_CallbackFunctionPointer;
  int Tool_DeInit_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Tool_DeInit_CallInstance;
  char Tool_SetMode_u8_IgnoreBool;
  uint8_t Tool_SetMode_u8_FinalReturn;
  char Tool_SetMode_u8_CallbackBool;
  CMOCK_Tool_SetMode_u8_CALLBACK Tool_SetMode_u8_CallbackFunctionPointer;
  int Tool_SetMode_u8_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Tool_SetMode_u8_CallInstance;
  char Tool_GetStatus_u32_IgnoreBool;
  uint32_t Tool_GetStatus_u32_FinalReturn;
  char Tool_GetStatus_u32_CallbackBool;
  CMOCK_Tool_GetStatus_u32_CALLBACK Tool_GetStatus_u32_CallbackFunctionPointer;
  int Tool_GetStatus_u32_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Tool_GetStatus_u32_CallInstance;
  char Tool_ComputeCrc_u32_IgnoreBool;
  uint32_t Tool_ComputeCrc_u32_FinalReturn;
  char Tool_ComputeCrc_u32_CallbackBool;
  CMOCK_Tool_ComputeCrc_u32_CALLBACK Tool_ComputeCrc_u32_CallbackFunctionPointer;
  int Tool_ComputeCrc_u32_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Tool_ComputeCrc_u32_CallInstance;
  char Tool_Push_u8_IgnoreBool;
  uint8_t Tool_Push_u8_FinalReturn;
  char Tool_Push_u8_CallbackBool;
  CMOCK_Tool_Push_u8_CALLBACK Tool_Push_u8_CallbackFunctionPointer;
  int Tool_Push_u8_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Tool_Push_u8_CallInstance;
  char Tool_Pop_u8_IgnoreBool;
  uint8_t Tool_Pop_u8_FinalReturn;
  char Tool_Pop_u8_CallbackBool;
  CMOCK_Tool_Pop_u8_CALLBACK Tool_Pop_u8_CallbackFunctionPointer;
  int Tool_Pop_u8_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Tool_Pop_u8_CallInstance;
  char Tool_RunTst_u8_IgnoreBool;
  uint8_t Tool_RunTst_u8_FinalReturn;
  char Tool_RunTst_u8_CallbackBool;
  CMOCK_Tool_RunTst_u8_CALLBACK Tool_RunTst_u8_CallbackFunctionPointer;
  int Tool_RunTst_u8_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Tool_RunTst_u8_CallInstance;
  char ModuleName_FunctionEx__IgnoreBool;
  uint8_t ModuleName_FunctionEx__FinalReturn;
  char ModuleName_FunctionEx__CallbackBool;
  CMOCK_ModuleName_FunctionEx__CALLBACK ModuleName_FunctionEx__CallbackFunctionPointer;
  int ModuleName_FunctionEx__CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ModuleName_FunctionEx__CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_Tool_Verify(void) {
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.Tool_Init_CallInstance;
  if(Mock.Tool_Init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if(CMOCK_GUTS_NONE != call_instance) {
    UNITY_SET_DETAIL(CMockString_Tool_Init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if(Mock.Tool_Init_CallbackFunctionPointer != NULL) {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Tool_DeInit_CallInstance;
  if(Mock.Tool_DeInit_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if(CMOCK_GUTS_NONE != call_instance) {
    UNITY_SET_DETAIL(CMockString_Tool_DeInit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if(Mock.Tool_DeInit_CallbackFunctionPointer != NULL) {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Tool_SetMode_u8_CallInstance;
  if(Mock.Tool_SetMode_u8_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if(CMOCK_GUTS_NONE != call_instance) {
    UNITY_SET_DETAIL(CMockString_Tool_SetMode_u8);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if(Mock.Tool_SetMode_u8_CallbackFunctionPointer != NULL) {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Tool_GetStatus_u32_CallInstance;
  if(Mock.Tool_GetStatus_u32_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if(CMOCK_GUTS_NONE != call_instance) {
    UNITY_SET_DETAIL(CMockString_Tool_GetStatus_u32);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if(Mock.Tool_GetStatus_u32_CallbackFunctionPointer != NULL) {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Tool_ComputeCrc_u32_CallInstance;
  if(Mock.Tool_ComputeCrc_u32_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if(CMOCK_GUTS_NONE != call_instance) {
    UNITY_SET_DETAIL(CMockString_Tool_ComputeCrc_u32);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if(Mock.Tool_ComputeCrc_u32_CallbackFunctionPointer != NULL) {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Tool_Push_u8_CallInstance;
  if(Mock.Tool_Push_u8_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if(CMOCK_GUTS_NONE != call_instance) {
    UNITY_SET_DETAIL(CMockString_Tool_Push_u8);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if(Mock.Tool_Push_u8_CallbackFunctionPointer != NULL) {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Tool_Pop_u8_CallInstance;
  if(Mock.Tool_Pop_u8_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if(CMOCK_GUTS_NONE != call_instance) {
    UNITY_SET_DETAIL(CMockString_Tool_Pop_u8);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if(Mock.Tool_Pop_u8_CallbackFunctionPointer != NULL) {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Tool_RunTst_u8_CallInstance;
  if(Mock.Tool_RunTst_u8_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if(CMOCK_GUTS_NONE != call_instance) {
    UNITY_SET_DETAIL(CMockString_Tool_RunTst_u8);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if(Mock.Tool_RunTst_u8_CallbackFunctionPointer != NULL) {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.ModuleName_FunctionEx__CallInstance;
  if(Mock.ModuleName_FunctionEx__IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if(CMOCK_GUTS_NONE != call_instance) {
    UNITY_SET_DETAIL(CMockString_ModuleName_FunctionEx_);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if(Mock.ModuleName_FunctionEx__CallbackFunctionPointer != NULL) {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_Tool_Init(void) { mock_Tool_Destroy(); }

void mock_Tool_Destroy(void) {
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void Tool_Init(void) {
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Tool_Init_CALL_INSTANCE *cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Tool_Init);
  cmock_call_instance = (CMOCK_Tool_Init_CALL_INSTANCE *)CMock_Guts_GetAddressFor(Mock.Tool_Init_CallInstance);
  Mock.Tool_Init_CallInstance = CMock_Guts_MemNext(Mock.Tool_Init_CallInstance);
  if(Mock.Tool_Init_IgnoreBool) {
    UNITY_CLR_DETAILS();
    return;
  }
  if(!Mock.Tool_Init_CallbackBool && Mock.Tool_Init_CallbackFunctionPointer != NULL) {
    Mock.Tool_Init_CallbackFunctionPointer(Mock.Tool_Init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if(cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if(cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if(Mock.Tool_Init_CallbackFunctionPointer != NULL) {
    Mock.Tool_Init_CallbackFunctionPointer(Mock.Tool_Init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void Tool_Init_CMockIgnore(void) { Mock.Tool_Init_IgnoreBool = (char)1; }

void Tool_Init_CMockStopIgnore(void) { Mock.Tool_Init_IgnoreBool = (char)0; }

void Tool_Init_CMockExpect(UNITY_LINE_TYPE cmock_line) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Tool_Init_CALL_INSTANCE));
  CMOCK_Tool_Init_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_Init_CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Tool_Init_CallInstance = CMock_Guts_MemChain(Mock.Tool_Init_CallInstance, cmock_guts_index);
  Mock.Tool_Init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void Tool_Init_AddCallback(CMOCK_Tool_Init_CALLBACK Callback) {
  Mock.Tool_Init_IgnoreBool = (char)0;
  Mock.Tool_Init_CallbackBool = (char)1;
  Mock.Tool_Init_CallbackFunctionPointer = Callback;
}

void Tool_Init_Stub(CMOCK_Tool_Init_CALLBACK Callback) {
  Mock.Tool_Init_IgnoreBool = (char)0;
  Mock.Tool_Init_CallbackBool = (char)0;
  Mock.Tool_Init_CallbackFunctionPointer = Callback;
}

void Tool_DeInit(void) {
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Tool_DeInit_CALL_INSTANCE *cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Tool_DeInit);
  cmock_call_instance = (CMOCK_Tool_DeInit_CALL_INSTANCE *)CMock_Guts_GetAddressFor(Mock.Tool_DeInit_CallInstance);
  Mock.Tool_DeInit_CallInstance = CMock_Guts_MemNext(Mock.Tool_DeInit_CallInstance);
  if(Mock.Tool_DeInit_IgnoreBool) {
    UNITY_CLR_DETAILS();
    return;
  }
  if(!Mock.Tool_DeInit_CallbackBool && Mock.Tool_DeInit_CallbackFunctionPointer != NULL) {
    Mock.Tool_DeInit_CallbackFunctionPointer(Mock.Tool_DeInit_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if(cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if(cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if(Mock.Tool_DeInit_CallbackFunctionPointer != NULL) {
    Mock.Tool_DeInit_CallbackFunctionPointer(Mock.Tool_DeInit_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void Tool_DeInit_CMockIgnore(void) { Mock.Tool_DeInit_IgnoreBool = (char)1; }

void Tool_DeInit_CMockStopIgnore(void) { Mock.Tool_DeInit_IgnoreBool = (char)0; }

void Tool_DeInit_CMockExpect(UNITY_LINE_TYPE cmock_line) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Tool_DeInit_CALL_INSTANCE));
  CMOCK_Tool_DeInit_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_DeInit_CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Tool_DeInit_CallInstance = CMock_Guts_MemChain(Mock.Tool_DeInit_CallInstance, cmock_guts_index);
  Mock.Tool_DeInit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void Tool_DeInit_AddCallback(CMOCK_Tool_DeInit_CALLBACK Callback) {
  Mock.Tool_DeInit_IgnoreBool = (char)0;
  Mock.Tool_DeInit_CallbackBool = (char)1;
  Mock.Tool_DeInit_CallbackFunctionPointer = Callback;
}

void Tool_DeInit_Stub(CMOCK_Tool_DeInit_CALLBACK Callback) {
  Mock.Tool_DeInit_IgnoreBool = (char)0;
  Mock.Tool_DeInit_CallbackBool = (char)0;
  Mock.Tool_DeInit_CallbackFunctionPointer = Callback;
}

uint8_t Tool_SetMode_u8(Tool_mode_e mode) {
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Tool_SetMode_u8_CALL_INSTANCE *cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Tool_SetMode_u8);
  cmock_call_instance = (CMOCK_Tool_SetMode_u8_CALL_INSTANCE *)CMock_Guts_GetAddressFor(Mock.Tool_SetMode_u8_CallInstance);
  Mock.Tool_SetMode_u8_CallInstance = CMock_Guts_MemNext(Mock.Tool_SetMode_u8_CallInstance);
  if(Mock.Tool_SetMode_u8_IgnoreBool) {
    UNITY_CLR_DETAILS();
    if(cmock_call_instance == NULL)
      return Mock.Tool_SetMode_u8_FinalReturn;
    Mock.Tool_SetMode_u8_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if(!Mock.Tool_SetMode_u8_CallbackBool && Mock.Tool_SetMode_u8_CallbackFunctionPointer != NULL) {
    uint8_t cmock_cb_ret = Mock.Tool_SetMode_u8_CallbackFunctionPointer(mode, Mock.Tool_SetMode_u8_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if(cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if(cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if(!cmock_call_instance->ExpectAnyArgsBool) {
    if(!cmock_call_instance->IgnoreArg_mode) {
      UNITY_SET_DETAILS(CMockString_Tool_SetMode_u8, CMockString_mode);
      UNITY_TEST_ASSERT_EQUAL_MEMORY((void *)(&cmock_call_instance->Expected_mode), (void *)(&mode), sizeof(Tool_mode_e), cmock_line, CMockStringMismatch);
    }
  }
  if(Mock.Tool_SetMode_u8_CallbackFunctionPointer != NULL) {
    cmock_call_instance->ReturnVal = Mock.Tool_SetMode_u8_CallbackFunctionPointer(mode, Mock.Tool_SetMode_u8_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_Tool_SetMode_u8(CMOCK_Tool_SetMode_u8_CALL_INSTANCE *cmock_call_instance, Tool_mode_e mode);
void CMockExpectParameters_Tool_SetMode_u8(CMOCK_Tool_SetMode_u8_CALL_INSTANCE *cmock_call_instance, Tool_mode_e mode) {
  memcpy((void *)(&cmock_call_instance->Expected_mode), (void *)(&mode),
         sizeof(Tool_mode_e[sizeof(mode) == sizeof(Tool_mode_e) ? 1 : -1])); /* add Tool_mode_e to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_mode = 0;
}

void Tool_SetMode_u8_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Tool_SetMode_u8_CALL_INSTANCE));
  CMOCK_Tool_SetMode_u8_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_SetMode_u8_CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Tool_SetMode_u8_CallInstance = CMock_Guts_MemChain(Mock.Tool_SetMode_u8_CallInstance, cmock_guts_index);
  Mock.Tool_SetMode_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.Tool_SetMode_u8_IgnoreBool = (char)1;
}

void Tool_SetMode_u8_CMockStopIgnore(void) {
  if(Mock.Tool_SetMode_u8_IgnoreBool)
    Mock.Tool_SetMode_u8_CallInstance = CMock_Guts_MemNext(Mock.Tool_SetMode_u8_CallInstance);
  Mock.Tool_SetMode_u8_IgnoreBool = (char)0;
}

void Tool_SetMode_u8_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Tool_SetMode_u8_CALL_INSTANCE));
  CMOCK_Tool_SetMode_u8_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_SetMode_u8_CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Tool_SetMode_u8_CallInstance = CMock_Guts_MemChain(Mock.Tool_SetMode_u8_CallInstance, cmock_guts_index);
  Mock.Tool_SetMode_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void Tool_SetMode_u8_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, Tool_mode_e mode, uint8_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Tool_SetMode_u8_CALL_INSTANCE));
  CMOCK_Tool_SetMode_u8_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_SetMode_u8_CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Tool_SetMode_u8_CallInstance = CMock_Guts_MemChain(Mock.Tool_SetMode_u8_CallInstance, cmock_guts_index);
  Mock.Tool_SetMode_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_Tool_SetMode_u8(cmock_call_instance, mode);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Tool_SetMode_u8_AddCallback(CMOCK_Tool_SetMode_u8_CALLBACK Callback) {
  Mock.Tool_SetMode_u8_IgnoreBool = (char)0;
  Mock.Tool_SetMode_u8_CallbackBool = (char)1;
  Mock.Tool_SetMode_u8_CallbackFunctionPointer = Callback;
}

void Tool_SetMode_u8_Stub(CMOCK_Tool_SetMode_u8_CALLBACK Callback) {
  Mock.Tool_SetMode_u8_IgnoreBool = (char)0;
  Mock.Tool_SetMode_u8_CallbackBool = (char)0;
  Mock.Tool_SetMode_u8_CallbackFunctionPointer = Callback;
}

void Tool_SetMode_u8_CMockIgnoreArg_mode(UNITY_LINE_TYPE cmock_line) {
  CMOCK_Tool_SetMode_u8_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_SetMode_u8_CALL_INSTANCE *)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Tool_SetMode_u8_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mode = 1;
}

uint32_t Tool_GetStatus_u32(void) {
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Tool_GetStatus_u32_CALL_INSTANCE *cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Tool_GetStatus_u32);
  cmock_call_instance = (CMOCK_Tool_GetStatus_u32_CALL_INSTANCE *)CMock_Guts_GetAddressFor(Mock.Tool_GetStatus_u32_CallInstance);
  Mock.Tool_GetStatus_u32_CallInstance = CMock_Guts_MemNext(Mock.Tool_GetStatus_u32_CallInstance);
  if(Mock.Tool_GetStatus_u32_IgnoreBool) {
    UNITY_CLR_DETAILS();
    if(cmock_call_instance == NULL)
      return Mock.Tool_GetStatus_u32_FinalReturn;
    Mock.Tool_GetStatus_u32_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if(!Mock.Tool_GetStatus_u32_CallbackBool && Mock.Tool_GetStatus_u32_CallbackFunctionPointer != NULL) {
    uint32_t cmock_cb_ret = Mock.Tool_GetStatus_u32_CallbackFunctionPointer(Mock.Tool_GetStatus_u32_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if(cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if(cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if(Mock.Tool_GetStatus_u32_CallbackFunctionPointer != NULL) {
    cmock_call_instance->ReturnVal = Mock.Tool_GetStatus_u32_CallbackFunctionPointer(Mock.Tool_GetStatus_u32_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void Tool_GetStatus_u32_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Tool_GetStatus_u32_CALL_INSTANCE));
  CMOCK_Tool_GetStatus_u32_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_GetStatus_u32_CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Tool_GetStatus_u32_CallInstance = CMock_Guts_MemChain(Mock.Tool_GetStatus_u32_CallInstance, cmock_guts_index);
  Mock.Tool_GetStatus_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.Tool_GetStatus_u32_IgnoreBool = (char)1;
}

void Tool_GetStatus_u32_CMockStopIgnore(void) {
  if(Mock.Tool_GetStatus_u32_IgnoreBool)
    Mock.Tool_GetStatus_u32_CallInstance = CMock_Guts_MemNext(Mock.Tool_GetStatus_u32_CallInstance);
  Mock.Tool_GetStatus_u32_IgnoreBool = (char)0;
}

void Tool_GetStatus_u32_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Tool_GetStatus_u32_CALL_INSTANCE));
  CMOCK_Tool_GetStatus_u32_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_GetStatus_u32_CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Tool_GetStatus_u32_CallInstance = CMock_Guts_MemChain(Mock.Tool_GetStatus_u32_CallInstance, cmock_guts_index);
  Mock.Tool_GetStatus_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Tool_GetStatus_u32_AddCallback(CMOCK_Tool_GetStatus_u32_CALLBACK Callback) {
  Mock.Tool_GetStatus_u32_IgnoreBool = (char)0;
  Mock.Tool_GetStatus_u32_CallbackBool = (char)1;
  Mock.Tool_GetStatus_u32_CallbackFunctionPointer = Callback;
}

void Tool_GetStatus_u32_Stub(CMOCK_Tool_GetStatus_u32_CALLBACK Callback) {
  Mock.Tool_GetStatus_u32_IgnoreBool = (char)0;
  Mock.Tool_GetStatus_u32_CallbackBool = (char)0;
  Mock.Tool_GetStatus_u32_CallbackFunctionPointer = Callback;
}

uint32_t Tool_ComputeCrc_u32(const uint8_t *data_pcu8, uint32_t length_u32) {
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE *cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Tool_ComputeCrc_u32);
  cmock_call_instance = (CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE *)CMock_Guts_GetAddressFor(Mock.Tool_ComputeCrc_u32_CallInstance);
  Mock.Tool_ComputeCrc_u32_CallInstance = CMock_Guts_MemNext(Mock.Tool_ComputeCrc_u32_CallInstance);
  if(Mock.Tool_ComputeCrc_u32_IgnoreBool) {
    UNITY_CLR_DETAILS();
    if(cmock_call_instance == NULL)
      return Mock.Tool_ComputeCrc_u32_FinalReturn;
    Mock.Tool_ComputeCrc_u32_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if(!Mock.Tool_ComputeCrc_u32_CallbackBool && Mock.Tool_ComputeCrc_u32_CallbackFunctionPointer != NULL) {
    uint32_t cmock_cb_ret = Mock.Tool_ComputeCrc_u32_CallbackFunctionPointer(data_pcu8, length_u32, Mock.Tool_ComputeCrc_u32_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if(cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if(cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if(!cmock_call_instance->ExpectAnyArgsBool) {
    if(!cmock_call_instance->IgnoreArg_data_pcu8) {
      UNITY_SET_DETAILS(CMockString_Tool_ComputeCrc_u32, CMockString_data_pcu8);
      if(cmock_call_instance->Expected_data_pcu8 == NULL) {
        UNITY_TEST_ASSERT_NULL(data_pcu8, cmock_line, CMockStringExpNULL);
      } else {
        UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data_pcu8, data_pcu8, cmock_call_instance->Expected_data_pcu8_Depth, cmock_line, CMockStringMismatch);
      }
    }
    if(!cmock_call_instance->IgnoreArg_length_u32) {
      UNITY_SET_DETAILS(CMockString_Tool_ComputeCrc_u32, CMockString_length_u32);
      UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_length_u32, length_u32, cmock_line, CMockStringMismatch);
    }
  }
  if(Mock.Tool_ComputeCrc_u32_CallbackFunctionPointer != NULL) {
    cmock_call_instance->ReturnVal = Mock.Tool_ComputeCrc_u32_CallbackFunctionPointer(data_pcu8, length_u32, Mock.Tool_ComputeCrc_u32_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_Tool_ComputeCrc_u32(CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE *cmock_call_instance, const uint8_t *data_pcu8, int data_pcu8_Depth, uint32_t length_u32);
void CMockExpectParameters_Tool_ComputeCrc_u32(CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE *cmock_call_instance, const uint8_t *data_pcu8, int data_pcu8_Depth, uint32_t length_u32) {
  cmock_call_instance->Expected_data_pcu8 = data_pcu8;
  cmock_call_instance->Expected_data_pcu8_Depth = data_pcu8_Depth;
  cmock_call_instance->IgnoreArg_data_pcu8 = 0;
  cmock_call_instance->Expected_length_u32 = length_u32;
  cmock_call_instance->IgnoreArg_length_u32 = 0;
}

void Tool_ComputeCrc_u32_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE));
  CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Tool_ComputeCrc_u32_CallInstance = CMock_Guts_MemChain(Mock.Tool_ComputeCrc_u32_CallInstance, cmock_guts_index);
  Mock.Tool_ComputeCrc_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.Tool_ComputeCrc_u32_IgnoreBool = (char)1;
}

void Tool_ComputeCrc_u32_CMockStopIgnore(void) {
  if(Mock.Tool_ComputeCrc_u32_IgnoreBool)
    Mock.Tool_ComputeCrc_u32_CallInstance = CMock_Guts_MemNext(Mock.Tool_ComputeCrc_u32_CallInstance);
  Mock.Tool_ComputeCrc_u32_IgnoreBool = (char)0;
}

void Tool_ComputeCrc_u32_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE));
  CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Tool_ComputeCrc_u32_CallInstance = CMock_Guts_MemChain(Mock.Tool_ComputeCrc_u32_CallInstance, cmock_guts_index);
  Mock.Tool_ComputeCrc_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void Tool_ComputeCrc_u32_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t *data_pcu8, uint32_t length_u32, uint32_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE));
  CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Tool_ComputeCrc_u32_CallInstance = CMock_Guts_MemChain(Mock.Tool_ComputeCrc_u32_CallInstance, cmock_guts_index);
  Mock.Tool_ComputeCrc_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_Tool_ComputeCrc_u32(cmock_call_instance, data_pcu8, 1, length_u32);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Tool_ComputeCrc_u32_AddCallback(CMOCK_Tool_ComputeCrc_u32_CALLBACK Callback) {
  Mock.Tool_ComputeCrc_u32_IgnoreBool = (char)0;
  Mock.Tool_ComputeCrc_u32_CallbackBool = (char)1;
  Mock.Tool_ComputeCrc_u32_CallbackFunctionPointer = Callback;
}

void Tool_ComputeCrc_u32_Stub(CMOCK_Tool_ComputeCrc_u32_CALLBACK Callback) {
  Mock.Tool_ComputeCrc_u32_IgnoreBool = (char)0;
  Mock.Tool_ComputeCrc_u32_CallbackBool = (char)0;
  Mock.Tool_ComputeCrc_u32_CallbackFunctionPointer = Callback;
}

void Tool_ComputeCrc_u32_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t *data_pcu8, int data_pcu8_Depth, uint32_t length_u32, uint32_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE));
  CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Tool_ComputeCrc_u32_CallInstance = CMock_Guts_MemChain(Mock.Tool_ComputeCrc_u32_CallInstance, cmock_guts_index);
  Mock.Tool_ComputeCrc_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_Tool_ComputeCrc_u32(cmock_call_instance, data_pcu8, data_pcu8_Depth, length_u32);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Tool_ComputeCrc_u32_CMockIgnoreArg_data_pcu8(UNITY_LINE_TYPE cmock_line) {
  CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE *)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Tool_ComputeCrc_u32_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_data_pcu8 = 1;
}

void Tool_ComputeCrc_u32_CMockIgnoreArg_length_u32(UNITY_LINE_TYPE cmock_line) {
  CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_ComputeCrc_u32_CALL_INSTANCE *)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Tool_ComputeCrc_u32_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_length_u32 = 1;
}

uint8_t Tool_Push_u8(uint8_t value_u8) {
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Tool_Push_u8_CALL_INSTANCE *cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Tool_Push_u8);
  cmock_call_instance = (CMOCK_Tool_Push_u8_CALL_INSTANCE *)CMock_Guts_GetAddressFor(Mock.Tool_Push_u8_CallInstance);
  Mock.Tool_Push_u8_CallInstance = CMock_Guts_MemNext(Mock.Tool_Push_u8_CallInstance);
  if(Mock.Tool_Push_u8_IgnoreBool) {
    UNITY_CLR_DETAILS();
    if(cmock_call_instance == NULL)
      return Mock.Tool_Push_u8_FinalReturn;
    Mock.Tool_Push_u8_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if(!Mock.Tool_Push_u8_CallbackBool && Mock.Tool_Push_u8_CallbackFunctionPointer != NULL) {
    uint8_t cmock_cb_ret = Mock.Tool_Push_u8_CallbackFunctionPointer(value_u8, Mock.Tool_Push_u8_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if(cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if(cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if(!cmock_call_instance->ExpectAnyArgsBool) {
    if(!cmock_call_instance->IgnoreArg_value_u8) {
      UNITY_SET_DETAILS(CMockString_Tool_Push_u8, CMockString_value_u8);
      UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_value_u8, value_u8, cmock_line, CMockStringMismatch);
    }
  }
  if(Mock.Tool_Push_u8_CallbackFunctionPointer != NULL) {
    cmock_call_instance->ReturnVal = Mock.Tool_Push_u8_CallbackFunctionPointer(value_u8, Mock.Tool_Push_u8_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_Tool_Push_u8(CMOCK_Tool_Push_u8_CALL_INSTANCE *cmock_call_instance, uint8_t value_u8);
void CMockExpectParameters_Tool_Push_u8(CMOCK_Tool_Push_u8_CALL_INSTANCE *cmock_call_instance, uint8_t value_u8) {
  cmock_call_instance->Expected_value_u8 = value_u8;
  cmock_call_instance->IgnoreArg_value_u8 = 0;
}

void Tool_Push_u8_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Tool_Push_u8_CALL_INSTANCE));
  CMOCK_Tool_Push_u8_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_Push_u8_CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Tool_Push_u8_CallInstance = CMock_Guts_MemChain(Mock.Tool_Push_u8_CallInstance, cmock_guts_index);
  Mock.Tool_Push_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.Tool_Push_u8_IgnoreBool = (char)1;
}

void Tool_Push_u8_CMockStopIgnore(void) {
  if(Mock.Tool_Push_u8_IgnoreBool)
    Mock.Tool_Push_u8_CallInstance = CMock_Guts_MemNext(Mock.Tool_Push_u8_CallInstance);
  Mock.Tool_Push_u8_IgnoreBool = (char)0;
}

void Tool_Push_u8_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Tool_Push_u8_CALL_INSTANCE));
  CMOCK_Tool_Push_u8_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_Push_u8_CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Tool_Push_u8_CallInstance = CMock_Guts_MemChain(Mock.Tool_Push_u8_CallInstance, cmock_guts_index);
  Mock.Tool_Push_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void Tool_Push_u8_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t value_u8, uint8_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Tool_Push_u8_CALL_INSTANCE));
  CMOCK_Tool_Push_u8_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_Push_u8_CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Tool_Push_u8_CallInstance = CMock_Guts_MemChain(Mock.Tool_Push_u8_CallInstance, cmock_guts_index);
  Mock.Tool_Push_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_Tool_Push_u8(cmock_call_instance, value_u8);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Tool_Push_u8_AddCallback(CMOCK_Tool_Push_u8_CALLBACK Callback) {
  Mock.Tool_Push_u8_IgnoreBool = (char)0;
  Mock.Tool_Push_u8_CallbackBool = (char)1;
  Mock.Tool_Push_u8_CallbackFunctionPointer = Callback;
}

void Tool_Push_u8_Stub(CMOCK_Tool_Push_u8_CALLBACK Callback) {
  Mock.Tool_Push_u8_IgnoreBool = (char)0;
  Mock.Tool_Push_u8_CallbackBool = (char)0;
  Mock.Tool_Push_u8_CallbackFunctionPointer = Callback;
}

void Tool_Push_u8_CMockIgnoreArg_value_u8(UNITY_LINE_TYPE cmock_line) {
  CMOCK_Tool_Push_u8_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_Push_u8_CALL_INSTANCE *)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Tool_Push_u8_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_value_u8 = 1;
}

uint8_t Tool_Pop_u8(uint8_t *value_pu8) {
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Tool_Pop_u8_CALL_INSTANCE *cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Tool_Pop_u8);
  cmock_call_instance = (CMOCK_Tool_Pop_u8_CALL_INSTANCE *)CMock_Guts_GetAddressFor(Mock.Tool_Pop_u8_CallInstance);
  Mock.Tool_Pop_u8_CallInstance = CMock_Guts_MemNext(Mock.Tool_Pop_u8_CallInstance);
  if(Mock.Tool_Pop_u8_IgnoreBool) {
    UNITY_CLR_DETAILS();
    if(cmock_call_instance == NULL)
      return Mock.Tool_Pop_u8_FinalReturn;
    Mock.Tool_Pop_u8_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if(!Mock.Tool_Pop_u8_CallbackBool && Mock.Tool_Pop_u8_CallbackFunctionPointer != NULL) {
    uint8_t cmock_cb_ret = Mock.Tool_Pop_u8_CallbackFunctionPointer(value_pu8, Mock.Tool_Pop_u8_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if(cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if(cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if(!cmock_call_instance->ExpectAnyArgsBool) {
    if(!cmock_call_instance->IgnoreArg_value_pu8) {
      UNITY_SET_DETAILS(CMockString_Tool_Pop_u8, CMockString_value_pu8);
      if(cmock_call_instance->Expected_value_pu8 == NULL) {
        UNITY_TEST_ASSERT_NULL(value_pu8, cmock_line, CMockStringExpNULL);
      } else {
        UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_value_pu8, value_pu8, cmock_call_instance->Expected_value_pu8_Depth, cmock_line, CMockStringMismatch);
      }
    }
  }
  if(Mock.Tool_Pop_u8_CallbackFunctionPointer != NULL) {
    cmock_call_instance->ReturnVal = Mock.Tool_Pop_u8_CallbackFunctionPointer(value_pu8, Mock.Tool_Pop_u8_CallbackCalls++);
  }
  if(cmock_call_instance->ReturnThruPtr_value_pu8_Used) {
    UNITY_TEST_ASSERT_NOT_NULL(value_pu8, cmock_line, CMockStringPtrIsNULL);
    memcpy((void *)value_pu8, (const void *)cmock_call_instance->ReturnThruPtr_value_pu8_Val, cmock_call_instance->ReturnThruPtr_value_pu8_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_Tool_Pop_u8(CMOCK_Tool_Pop_u8_CALL_INSTANCE *cmock_call_instance, uint8_t *value_pu8, int value_pu8_Depth);
void CMockExpectParameters_Tool_Pop_u8(CMOCK_Tool_Pop_u8_CALL_INSTANCE *cmock_call_instance, uint8_t *value_pu8, int value_pu8_Depth) {
  cmock_call_instance->Expected_value_pu8 = value_pu8;
  cmock_call_instance->Expected_value_pu8_Depth = value_pu8_Depth;
  cmock_call_instance->IgnoreArg_value_pu8 = 0;
  cmock_call_instance->ReturnThruPtr_value_pu8_Used = 0;
}

void Tool_Pop_u8_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Tool_Pop_u8_CALL_INSTANCE));
  CMOCK_Tool_Pop_u8_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_Pop_u8_CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Tool_Pop_u8_CallInstance = CMock_Guts_MemChain(Mock.Tool_Pop_u8_CallInstance, cmock_guts_index);
  Mock.Tool_Pop_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.Tool_Pop_u8_IgnoreBool = (char)1;
}

void Tool_Pop_u8_CMockStopIgnore(void) {
  if(Mock.Tool_Pop_u8_IgnoreBool)
    Mock.Tool_Pop_u8_CallInstance = CMock_Guts_MemNext(Mock.Tool_Pop_u8_CallInstance);
  Mock.Tool_Pop_u8_IgnoreBool = (char)0;
}

void Tool_Pop_u8_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Tool_Pop_u8_CALL_INSTANCE));
  CMOCK_Tool_Pop_u8_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_Pop_u8_CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Tool_Pop_u8_CallInstance = CMock_Guts_MemChain(Mock.Tool_Pop_u8_CallInstance, cmock_guts_index);
  Mock.Tool_Pop_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void Tool_Pop_u8_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t *value_pu8, uint8_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Tool_Pop_u8_CALL_INSTANCE));
  CMOCK_Tool_Pop_u8_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_Pop_u8_CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Tool_Pop_u8_CallInstance = CMock_Guts_MemChain(Mock.Tool_Pop_u8_CallInstance, cmock_guts_index);
  Mock.Tool_Pop_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_Tool_Pop_u8(cmock_call_instance, value_pu8, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Tool_Pop_u8_AddCallback(CMOCK_Tool_Pop_u8_CALLBACK Callback) {
  Mock.Tool_Pop_u8_IgnoreBool = (char)0;
  Mock.Tool_Pop_u8_CallbackBool = (char)1;
  Mock.Tool_Pop_u8_CallbackFunctionPointer = Callback;
}

void Tool_Pop_u8_Stub(CMOCK_Tool_Pop_u8_CALLBACK Callback) {
  Mock.Tool_Pop_u8_IgnoreBool = (char)0;
  Mock.Tool_Pop_u8_CallbackBool = (char)0;
  Mock.Tool_Pop_u8_CallbackFunctionPointer = Callback;
}

void Tool_Pop_u8_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t *value_pu8, int value_pu8_Depth, uint8_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Tool_Pop_u8_CALL_INSTANCE));
  CMOCK_Tool_Pop_u8_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_Pop_u8_CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Tool_Pop_u8_CallInstance = CMock_Guts_MemChain(Mock.Tool_Pop_u8_CallInstance, cmock_guts_index);
  Mock.Tool_Pop_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_Tool_Pop_u8(cmock_call_instance, value_pu8, value_pu8_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Tool_Pop_u8_CMockReturnMemThruPtr_value_pu8(UNITY_LINE_TYPE cmock_line, uint8_t const *value_pu8, size_t cmock_size) {
  CMOCK_Tool_Pop_u8_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_Pop_u8_CALL_INSTANCE *)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Tool_Pop_u8_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_value_pu8_Used = 1;
  cmock_call_instance->ReturnThruPtr_value_pu8_Val = value_pu8;
  cmock_call_instance->ReturnThruPtr_value_pu8_Size = cmock_size;
}

void Tool_Pop_u8_CMockIgnoreArg_value_pu8(UNITY_LINE_TYPE cmock_line) {
  CMOCK_Tool_Pop_u8_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_Pop_u8_CALL_INSTANCE *)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Tool_Pop_u8_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_value_pu8 = 1;
}

uint8_t Tool_RunTst_u8(void) {
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Tool_RunTst_u8_CALL_INSTANCE *cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Tool_RunTst_u8);
  cmock_call_instance = (CMOCK_Tool_RunTst_u8_CALL_INSTANCE *)CMock_Guts_GetAddressFor(Mock.Tool_RunTst_u8_CallInstance);
  Mock.Tool_RunTst_u8_CallInstance = CMock_Guts_MemNext(Mock.Tool_RunTst_u8_CallInstance);
  if(Mock.Tool_RunTst_u8_IgnoreBool) {
    UNITY_CLR_DETAILS();
    if(cmock_call_instance == NULL)
      return Mock.Tool_RunTst_u8_FinalReturn;
    Mock.Tool_RunTst_u8_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if(!Mock.Tool_RunTst_u8_CallbackBool && Mock.Tool_RunTst_u8_CallbackFunctionPointer != NULL) {
    uint8_t cmock_cb_ret = Mock.Tool_RunTst_u8_CallbackFunctionPointer(Mock.Tool_RunTst_u8_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if(cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if(cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if(Mock.Tool_RunTst_u8_CallbackFunctionPointer != NULL) {
    cmock_call_instance->ReturnVal = Mock.Tool_RunTst_u8_CallbackFunctionPointer(Mock.Tool_RunTst_u8_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void Tool_RunTst_u8_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Tool_RunTst_u8_CALL_INSTANCE));
  CMOCK_Tool_RunTst_u8_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_RunTst_u8_CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Tool_RunTst_u8_CallInstance = CMock_Guts_MemChain(Mock.Tool_RunTst_u8_CallInstance, cmock_guts_index);
  Mock.Tool_RunTst_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.Tool_RunTst_u8_IgnoreBool = (char)1;
}

void Tool_RunTst_u8_CMockStopIgnore(void) {
  if(Mock.Tool_RunTst_u8_IgnoreBool)
    Mock.Tool_RunTst_u8_CallInstance = CMock_Guts_MemNext(Mock.Tool_RunTst_u8_CallInstance);
  Mock.Tool_RunTst_u8_IgnoreBool = (char)0;
}

void Tool_RunTst_u8_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Tool_RunTst_u8_CALL_INSTANCE));
  CMOCK_Tool_RunTst_u8_CALL_INSTANCE *cmock_call_instance = (CMOCK_Tool_RunTst_u8_CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Tool_RunTst_u8_CallInstance = CMock_Guts_MemChain(Mock.Tool_RunTst_u8_CallInstance, cmock_guts_index);
  Mock.Tool_RunTst_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Tool_RunTst_u8_AddCallback(CMOCK_Tool_RunTst_u8_CALLBACK Callback) {
  Mock.Tool_RunTst_u8_IgnoreBool = (char)0;
  Mock.Tool_RunTst_u8_CallbackBool = (char)1;
  Mock.Tool_RunTst_u8_CallbackFunctionPointer = Callback;
}

void Tool_RunTst_u8_Stub(CMOCK_Tool_RunTst_u8_CALLBACK Callback) {
  Mock.Tool_RunTst_u8_IgnoreBool = (char)0;
  Mock.Tool_RunTst_u8_CallbackBool = (char)0;
  Mock.Tool_RunTst_u8_CallbackFunctionPointer = Callback;
}

uint8_t ModuleName_FunctionEx_(uint32_t in_id_u32, int32_t in_mode_e, const uint8_t *in_cfg_pcu8, uint8_t *in_buf_pu8, uint16_t in_bufLen_u16, uint8_t *out_status_pu8) {
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_ModuleName_FunctionEx_);
  cmock_call_instance = (CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *)CMock_Guts_GetAddressFor(Mock.ModuleName_FunctionEx__CallInstance);
  Mock.ModuleName_FunctionEx__CallInstance = CMock_Guts_MemNext(Mock.ModuleName_FunctionEx__CallInstance);
  if(Mock.ModuleName_FunctionEx__IgnoreBool) {
    UNITY_CLR_DETAILS();
    if(cmock_call_instance == NULL)
      return Mock.ModuleName_FunctionEx__FinalReturn;
    Mock.ModuleName_FunctionEx__FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if(!Mock.ModuleName_FunctionEx__CallbackBool && Mock.ModuleName_FunctionEx__CallbackFunctionPointer != NULL) {
    uint8_t cmock_cb_ret =
        Mock.ModuleName_FunctionEx__CallbackFunctionPointer(in_id_u32, in_mode_e, in_cfg_pcu8, in_buf_pu8, in_bufLen_u16, out_status_pu8, Mock.ModuleName_FunctionEx__CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if(cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if(cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if(!cmock_call_instance->ExpectAnyArgsBool) {
    if(!cmock_call_instance->IgnoreArg_in_id_u32) {
      UNITY_SET_DETAILS(CMockString_ModuleName_FunctionEx_, CMockString_in_id_u32);
      UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_in_id_u32, in_id_u32, cmock_line, CMockStringMismatch);
    }
    if(!cmock_call_instance->IgnoreArg_in_mode_e) {
      UNITY_SET_DETAILS(CMockString_ModuleName_FunctionEx_, CMockString_in_mode_e);
      UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_in_mode_e, in_mode_e, cmock_line, CMockStringMismatch);
    }
    if(!cmock_call_instance->IgnoreArg_in_cfg_pcu8) {
      UNITY_SET_DETAILS(CMockString_ModuleName_FunctionEx_, CMockString_in_cfg_pcu8);
      if(cmock_call_instance->Expected_in_cfg_pcu8 == NULL) {
        UNITY_TEST_ASSERT_NULL(in_cfg_pcu8, cmock_line, CMockStringExpNULL);
      } else {
        UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_in_cfg_pcu8, in_cfg_pcu8, cmock_call_instance->Expected_in_cfg_pcu8_Depth, cmock_line, CMockStringMismatch);
      }
    }
    if(!cmock_call_instance->IgnoreArg_in_buf_pu8) {
      UNITY_SET_DETAILS(CMockString_ModuleName_FunctionEx_, CMockString_in_buf_pu8);
      if(cmock_call_instance->Expected_in_buf_pu8 == NULL) {
        UNITY_TEST_ASSERT_NULL(in_buf_pu8, cmock_line, CMockStringExpNULL);
      } else {
        UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_in_buf_pu8, in_buf_pu8, cmock_call_instance->Expected_in_buf_pu8_Depth, cmock_line, CMockStringMismatch);
      }
    }
    if(!cmock_call_instance->IgnoreArg_in_bufLen_u16) {
      UNITY_SET_DETAILS(CMockString_ModuleName_FunctionEx_, CMockString_in_bufLen_u16);
      UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_in_bufLen_u16, in_bufLen_u16, cmock_line, CMockStringMismatch);
    }
    if(!cmock_call_instance->IgnoreArg_out_status_pu8) {
      UNITY_SET_DETAILS(CMockString_ModuleName_FunctionEx_, CMockString_out_status_pu8);
      if(cmock_call_instance->Expected_out_status_pu8 == NULL) {
        UNITY_TEST_ASSERT_NULL(out_status_pu8, cmock_line, CMockStringExpNULL);
      } else {
        UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_out_status_pu8, out_status_pu8, cmock_call_instance->Expected_out_status_pu8_Depth, cmock_line, CMockStringMismatch);
      }
    }
  }
  if(Mock.ModuleName_FunctionEx__CallbackFunctionPointer != NULL) {
    cmock_call_instance->ReturnVal =
        Mock.ModuleName_FunctionEx__CallbackFunctionPointer(in_id_u32, in_mode_e, in_cfg_pcu8, in_buf_pu8, in_bufLen_u16, out_status_pu8, Mock.ModuleName_FunctionEx__CallbackCalls++);
  }
  if(cmock_call_instance->ReturnThruPtr_in_buf_pu8_Used) {
    UNITY_TEST_ASSERT_NOT_NULL(in_buf_pu8, cmock_line, CMockStringPtrIsNULL);
    memcpy((void *)in_buf_pu8, (const void *)cmock_call_instance->ReturnThruPtr_in_buf_pu8_Val, cmock_call_instance->ReturnThruPtr_in_buf_pu8_Size);
  }
  if(cmock_call_instance->ReturnThruPtr_out_status_pu8_Used) {
    UNITY_TEST_ASSERT_NOT_NULL(out_status_pu8, cmock_line, CMockStringPtrIsNULL);
    memcpy((void *)out_status_pu8, (const void *)cmock_call_instance->ReturnThruPtr_out_status_pu8_Val, cmock_call_instance->ReturnThruPtr_out_status_pu8_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_ModuleName_FunctionEx_(CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *cmock_call_instance, uint32_t in_id_u32, int32_t in_mode_e, const uint8_t *in_cfg_pcu8,
                                                  int in_cfg_pcu8_Depth, uint8_t *in_buf_pu8, int in_buf_pu8_Depth, uint16_t in_bufLen_u16, uint8_t *out_status_pu8, int out_status_pu8_Depth);
void CMockExpectParameters_ModuleName_FunctionEx_(CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *cmock_call_instance, uint32_t in_id_u32, int32_t in_mode_e, const uint8_t *in_cfg_pcu8,
                                                  int in_cfg_pcu8_Depth, uint8_t *in_buf_pu8, int in_buf_pu8_Depth, uint16_t in_bufLen_u16, uint8_t *out_status_pu8, int out_status_pu8_Depth) {
  cmock_call_instance->Expected_in_id_u32 = in_id_u32;
  cmock_call_instance->IgnoreArg_in_id_u32 = 0;
  cmock_call_instance->Expected_in_mode_e = in_mode_e;
  cmock_call_instance->IgnoreArg_in_mode_e = 0;
  cmock_call_instance->Expected_in_cfg_pcu8 = in_cfg_pcu8;
  cmock_call_instance->Expected_in_cfg_pcu8_Depth = in_cfg_pcu8_Depth;
  cmock_call_instance->IgnoreArg_in_cfg_pcu8 = 0;
  cmock_call_instance->Expected_in_buf_pu8 = in_buf_pu8;
  cmock_call_instance->Expected_in_buf_pu8_Depth = in_buf_pu8_Depth;
  cmock_call_instance->IgnoreArg_in_buf_pu8 = 0;
  cmock_call_instance->ReturnThruPtr_in_buf_pu8_Used = 0;
  cmock_call_instance->Expected_in_bufLen_u16 = in_bufLen_u16;
  cmock_call_instance->IgnoreArg_in_bufLen_u16 = 0;
  cmock_call_instance->Expected_out_status_pu8 = out_status_pu8;
  cmock_call_instance->Expected_out_status_pu8_Depth = out_status_pu8_Depth;
  cmock_call_instance->IgnoreArg_out_status_pu8 = 0;
  cmock_call_instance->ReturnThruPtr_out_status_pu8_Used = 0;
}

void ModuleName_FunctionEx__CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ModuleName_FunctionEx__CALL_INSTANCE));
  CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *cmock_call_instance = (CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ModuleName_FunctionEx__CallInstance = CMock_Guts_MemChain(Mock.ModuleName_FunctionEx__CallInstance, cmock_guts_index);
  Mock.ModuleName_FunctionEx__IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.ModuleName_FunctionEx__IgnoreBool = (char)1;
}

void ModuleName_FunctionEx__CMockStopIgnore(void) {
  if(Mock.ModuleName_FunctionEx__IgnoreBool)
    Mock.ModuleName_FunctionEx__CallInstance = CMock_Guts_MemNext(Mock.ModuleName_FunctionEx__CallInstance);
  Mock.ModuleName_FunctionEx__IgnoreBool = (char)0;
}

void ModuleName_FunctionEx__CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ModuleName_FunctionEx__CALL_INSTANCE));
  CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *cmock_call_instance = (CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ModuleName_FunctionEx__CallInstance = CMock_Guts_MemChain(Mock.ModuleName_FunctionEx__CallInstance, cmock_guts_index);
  Mock.ModuleName_FunctionEx__IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void ModuleName_FunctionEx__CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t in_id_u32, int32_t in_mode_e, const uint8_t *in_cfg_pcu8, uint8_t *in_buf_pu8, uint16_t in_bufLen_u16,
                                                 uint8_t *out_status_pu8, uint8_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ModuleName_FunctionEx__CALL_INSTANCE));
  CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *cmock_call_instance = (CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ModuleName_FunctionEx__CallInstance = CMock_Guts_MemChain(Mock.ModuleName_FunctionEx__CallInstance, cmock_guts_index);
  Mock.ModuleName_FunctionEx__IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_ModuleName_FunctionEx_(cmock_call_instance, in_id_u32, in_mode_e, in_cfg_pcu8, 1, in_buf_pu8, 1, in_bufLen_u16, out_status_pu8, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void ModuleName_FunctionEx__AddCallback(CMOCK_ModuleName_FunctionEx__CALLBACK Callback) {
  Mock.ModuleName_FunctionEx__IgnoreBool = (char)0;
  Mock.ModuleName_FunctionEx__CallbackBool = (char)1;
  Mock.ModuleName_FunctionEx__CallbackFunctionPointer = Callback;
}

void ModuleName_FunctionEx__Stub(CMOCK_ModuleName_FunctionEx__CALLBACK Callback) {
  Mock.ModuleName_FunctionEx__IgnoreBool = (char)0;
  Mock.ModuleName_FunctionEx__CallbackBool = (char)0;
  Mock.ModuleName_FunctionEx__CallbackFunctionPointer = Callback;
}

void ModuleName_FunctionEx__CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t in_id_u32, int32_t in_mode_e, const uint8_t *in_cfg_pcu8, int in_cfg_pcu8_Depth, uint8_t *in_buf_pu8,
                                                          int in_buf_pu8_Depth, uint16_t in_bufLen_u16, uint8_t *out_status_pu8, int out_status_pu8_Depth, uint8_t cmock_to_return) {
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ModuleName_FunctionEx__CALL_INSTANCE));
  CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *cmock_call_instance = (CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ModuleName_FunctionEx__CallInstance = CMock_Guts_MemChain(Mock.ModuleName_FunctionEx__CallInstance, cmock_guts_index);
  Mock.ModuleName_FunctionEx__IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_ModuleName_FunctionEx_(cmock_call_instance, in_id_u32, in_mode_e, in_cfg_pcu8, in_cfg_pcu8_Depth, in_buf_pu8, in_buf_pu8_Depth, in_bufLen_u16, out_status_pu8,
                                               out_status_pu8_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void ModuleName_FunctionEx__CMockReturnMemThruPtr_in_buf_pu8(UNITY_LINE_TYPE cmock_line, uint8_t const *in_buf_pu8, size_t cmock_size) {
  CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *cmock_call_instance =
      (CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ModuleName_FunctionEx__CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_in_buf_pu8_Used = 1;
  cmock_call_instance->ReturnThruPtr_in_buf_pu8_Val = in_buf_pu8;
  cmock_call_instance->ReturnThruPtr_in_buf_pu8_Size = cmock_size;
}

void ModuleName_FunctionEx__CMockReturnMemThruPtr_out_status_pu8(UNITY_LINE_TYPE cmock_line, uint8_t const *out_status_pu8, size_t cmock_size) {
  CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *cmock_call_instance =
      (CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ModuleName_FunctionEx__CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_out_status_pu8_Used = 1;
  cmock_call_instance->ReturnThruPtr_out_status_pu8_Val = out_status_pu8;
  cmock_call_instance->ReturnThruPtr_out_status_pu8_Size = cmock_size;
}

void ModuleName_FunctionEx__CMockIgnoreArg_in_id_u32(UNITY_LINE_TYPE cmock_line) {
  CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *cmock_call_instance =
      (CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ModuleName_FunctionEx__CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_in_id_u32 = 1;
}

void ModuleName_FunctionEx__CMockIgnoreArg_in_mode_e(UNITY_LINE_TYPE cmock_line) {
  CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *cmock_call_instance =
      (CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ModuleName_FunctionEx__CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_in_mode_e = 1;
}

void ModuleName_FunctionEx__CMockIgnoreArg_in_cfg_pcu8(UNITY_LINE_TYPE cmock_line) {
  CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *cmock_call_instance =
      (CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ModuleName_FunctionEx__CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_in_cfg_pcu8 = 1;
}

void ModuleName_FunctionEx__CMockIgnoreArg_in_buf_pu8(UNITY_LINE_TYPE cmock_line) {
  CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *cmock_call_instance =
      (CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ModuleName_FunctionEx__CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_in_buf_pu8 = 1;
}

void ModuleName_FunctionEx__CMockIgnoreArg_in_bufLen_u16(UNITY_LINE_TYPE cmock_line) {
  CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *cmock_call_instance =
      (CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ModuleName_FunctionEx__CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_in_bufLen_u16 = 1;
}

void ModuleName_FunctionEx__CMockIgnoreArg_out_status_pu8(UNITY_LINE_TYPE cmock_line) {
  CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *cmock_call_instance =
      (CMOCK_ModuleName_FunctionEx__CALL_INSTANCE *)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ModuleName_FunctionEx__CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_out_status_pu8 = 1;
}
